{% set version = "3.8.1.post1" %}
{% set name = "tinydb" %}
{% set sha = "961d7fbeb09843251b8a016965269c2fb0e898f16e8686bcf40e23d385219d78" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    fn: tinydb-{{ version }}.tar.gz
    sha256: {{ sha }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python

requirements:
    build:
        - setuptools
        - python
    run:
        - python

test:
    imports:
        - tinydb

about:
    home: https://github.com/msiemens/tinydb
    license: MIT
    license_family: MIT
    # license file is not included. Should raise this on upstream.
    #license_file: LICENCE
    summary: TinyDB is a tiny, document oriented database optimized for your happiness :)
    description: |
        TinyDB is a lightweight document oriented database optimized for your
        happiness :) It's written in pure Python and has no external
        dependencies. The target are small apps that would be blown away by a
        SQL-DB or an external database server.

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - msiemens
        - tacaswell
        - ericmjl
