# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OGzcrQ6FFMKibXw8YLpTh3P9HCbU38HlRujuEKO1Hs6PYF+LanfKjbJt3mTKxgB4mv69hn7d2IZez4SE1rtcvJQhbGTKSHDKKBRSfIOsE8xBD/cfoqupDkVvmBujCNBOJcGzT/jax1DkzDGNIiEhWKDwv+I7KArtt8yBdy+ieT6dcGcFdCVgGx+WQ7N/o8qNUAyWoxfcWbPtn678ZecFyJJcyy7L9DbNIFdUW02/7QzKU34BXcas2QWn1fSzMXew6T/+3UYh2ZraVPfkexiHYJ2W/seodXCA5eMsr1VkkQtK/L8BqJBNZmwqAXw3q1ZRvHbsV4EvA3t5kmk5KDifqzDDI2GC0wKaWZsiKb5ah0/GMJd46P0QXIs3fvIR09jpeaCKG53zUo/v9VJlTHmo03+wL/iS/rG5vhd1+Mertrh3o25T9E6hO2MCVW2m2M5/8Y8S6MV16FLxRqk4q0ce6DOYb/EU7vwS6kJYS45kOklznWpGW/sj/g1zbKFRq2Yx593KIgjndJjTor85vtmK84uQhZZ3YP524CMWYUCrOuIKPkAr5IqSLFnt5j7pB3pFGhFw6Bza2qUFsJ0OcrrybsAI4FPt6CaD1oGtI20FvC2oezKSodlkV/GvpaWDVkEMxmKqg22FjQDTaQZjPiLQVFhaEDSjdMOCaDlSh5oJwpE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
