travis:
  secure:
    BINSTAR_TOKEN: X5qq1csET3qdw8iPT6MT1vKXvbk9VmDKUQxLVUGj/QWDiKPg+Q2YM263bWgo9B1t3uyQKINKS+QXomMF+WAynwGAUkIDpOz1b4eMTvAcNhfux0L5TVzsDpZOG2R/Ru33iGBynlGBLJ4MzFdKLzFKgr1UYg/YX2g6fBI0SgMJtyOS9h5OrJV9E3CD86Jo8ofZTtoZhkTU6/5/gr6HBXNqFLXPdpVNzoRWa5XKVWzy9CG3s/JKFYA4AM4VgC3LcanTZnEfkXO5mfrxE/y9QhaWM8ps0/Tz+nvl6a5F5W18OghA4WYOmAsp3ITG0/KOhKXstHcg84gPWZArw3TOtqyKzUdaDdTeuC9g+VWE7/qPa+IudFbHTlloaph68Faj3x536B/51zjCQTHIAT7AdGcAyS33V8pP0avfpRtIpo6QVUAVmkUn+gjAqhWaav5pyDg5Hp3Ti0SM0FrRfchp/psyGgTBUgRN9qWskYUrH3T3khw9CcLSwI1CJ4DdOq+TCAzwERi7oKcAUMDaDSDQpgdEPMD1OXh3Z9mISbK8ekxnkNzTtMpcuMkc4dg4pNBU1OWNhHqRaEAmaonjyqKj5kDzpicjGVm6MZKT976jXhHFyHwbROOqyYTyg7ODkZpblvimF6FsTxpt/fVlnoT+1EdjoLeosrq3yaJLLFHjnGyKJzI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
