travis:
  secure:
    BINSTAR_TOKEN: gC0L/iE7cJvNv+Azyg2ojsqsywCMwrSttBBxJjMXEmnFaqaC/jWE2eag0li213ex1ctDqBuGL+ZPLUvHzZ7ET2Kd+DrDlBFqaK7vNmoctG2XGGCgXLXkU83W2l/kQL5QbXdD1eh3GRUpga+2lLkeXHOf6+rTOKy8PKyz/Le6LsJ0sLseTOfuLhAi8u8Zvrscvqiw8Ux7caKrXF3RgTRQMEqKZ2pHz1yCHRFA1whtFQu0UheVCcMztIFXEENR96GCwGA+/uHjoRpRsh2qV3kWtxbUarEIjrz/R1bkn3V3uxjj3jjo6qmHei4DAMgy6jRqNFSoouTBWJ0NleGNh7mrhu6rL6OPSavwvDd/JJ2t5u8D9KZoAYRzQ7YnaBM28PJSzcaXjb1XHWOiSRIlWXSeDlkAOZ9rLxizzuYlcQBKFYowLqpofDwpekeFbcdsGtqD4RVoDjzFefm3l7ClLPkN4xSIq3UFcbVGTutKgrj/z1dBeMBpWKkdpjlyHAUzPuI+O1UXGzGXr13G6HTeNdO3Qz89SMHw15eDmvQei0iro9orUIAvOtWvEYeJQ22u0sa8vMi17uNlHf0cUqbaRQdnq94nNuNQ9VsKdD5QBj0MVziGxDzRfiQizTaoJPbOgjSpVmZBaBRm0j0nJ0EA9jef4sjteafgmFIFxmI0C0XOj20=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
